### ISSUE TITLE
topAnchorDisplayObject, left, bottom, etc. are missing in AnchorLayoutData?

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathersui-openfl#16]

**Comment by joshtynjala** [comment]
Correct. They have not been implemented yet. I'm thinking about using a Haxe enum instead, so that you can optionally pass multiple values to `top`, `right`, `bottom`, and `left`. Hypothetically, something like this:

```hx
//relative to display object
layoutData.top = RelativeTo(target, 10);
```

As I understand it, I can use special metadata to allow you to pass in a number that will be automatically coerced into the enum, so this should still work too:

```hx
//relative to container edge
layoutData.top = 10;
```

It should be pretty cool because it might allow other types of anchoring, such as with percentages instead of pixels.

**Comment by CrazyFlasher** [comment]
Cool!

**Comment by CrazyFlasher** [comment]
Any updates about anchorDisplayObjects? :)

**Comment by joshtynjala** [comment]
Not yet. I'll try to give it some priority after GridView is further along.
