### ISSUE TITLE
Does IStyleProvider need to implement IEventDispatcher?

### ISSUE THREAD

**Issue by brighttank** [BowlerHatLLC/feathersui-openfl#36]
I'm trying to port a theme over from the starling version and this is causing an issue. I can't see anywhere in the code that requires IStyleProvider to implement the IEventDispatcher interface.

Am I missing something?

**Comment by brighttank** [comment]
Ah, I just saw where you're using it. I guess it's necessary after all.

**Comment by joshtynjala** [comment]
Just adding some details, in case this issue comes up when someone searches Google or whatever. 

FeathersControl listens for Event.CHANGE from the style provider. If the event is dispatched, the component will clear its styles and ask the style provider for new ones. Basically, it allows a style provider to be updated after creation and automatically update components that have already been styled. As an example of where this might be used, in the default theme, switching between dark mode and light mode will result in Event.CHANGE being dispatched so that all components are restyled.

**Comment by brighttank** [comment]
The theme switching ability is going to be awesome!
